"""update on model relationships

Revision ID: 40c4b097ba8c
Revises: f0ba62c225b3
Create Date: 2024-02-18 09:15:35.001104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c4b097ba8c'
down_revision: Union[str, None] = 'f0ba62c225b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('Joined_date', sa.DateTime(), nullable=True))
    op.drop_column('employees', 'start_date')
    op.add_column('managers', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.drop_column('managers', 'Joined_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('Joined_date', sa.DATETIME(), nullable=True))
    op.drop_column('managers', 'start_date')
    op.add_column('employees', sa.Column('start_date', sa.DATETIME(), nullable=True))
    op.drop_column('employees', 'Joined_date')
    # ### end Alembic commands ###
