"""relationships testing

Revision ID: 8ffe0eff9868
Revises: e2d26d52dc71
Create Date: 2024-02-17 18:45:40.741986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffe0eff9868'
down_revision: Union[str, None] = 'e2d26d52dc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('joined_date', sa.DateTime(), nullable=True))
    op.drop_column('employees', 'Joined_date')
    op.add_column('managers', sa.Column('joined_date', sa.DateTime(), nullable=True))
    op.drop_column('managers', 'Joined_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('Joined_date', sa.DATETIME(), nullable=True))
    op.drop_column('managers', 'joined_date')
    op.add_column('employees', sa.Column('Joined_date', sa.DATETIME(), nullable=True))
    op.drop_column('employees', 'joined_date')
    # ### end Alembic commands ###
