"""chnage on Column name

Revision ID: f0ba62c225b3
Revises: e2d26d52dc71
Create Date: 2024-02-18 09:05:42.415031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ba62c225b3'
down_revision: Union[str, None] = 'e2d26d52dc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.drop_column('employees', 'Joined_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('Joined_date', sa.DATETIME(), nullable=True))
    op.drop_column('employees', 'start_date')
    # ### end Alembic commands ###
